# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Empact-mongo_session_store}
  s.version = "1.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Nicolas Mérouze}, %q{Tony Pitale}, %q{Chris Brickley}]
  s.date = %q{2011-08-01}
  s.email = %q{nicolas.merouze@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "lib/mongo_session_store.rb",
    "lib/mongo_session_store/mongo_mapper.rb",
    "lib/mongo_session_store/mongoid.rb"
  ]
  s.homepage = %q{http://github.com/nmerouze/mongo_session_store}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Rails session store class implemented for MongoMapper and Mongoid}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, ["~> 2.3"])
      s.add_development_dependency(%q<mongo_mapper>, [">= 0.6.1"])
      s.add_development_dependency(%q<mongoid>, ["~> 1.0"])
    else
      s.add_dependency(%q<actionpack>, ["~> 2.3"])
      s.add_dependency(%q<mongo_mapper>, [">= 0.6.1"])
      s.add_dependency(%q<mongoid>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<actionpack>, ["~> 2.3"])
    s.add_dependency(%q<mongo_mapper>, [">= 0.6.1"])
    s.add_dependency(%q<mongoid>, ["~> 1.0"])
  end
end

